services:
  postgres:
    image: postgres:17
    container_name: innopolois_plm_resource_db
    restart: always
    environment:
      POSTGRES_USER: innopolois
      POSTGRES_PASSWORD: e11dea74f93bhh018009db29d4ggvce818dfb09c3ad945
      POSTGRES_DB: innopolois_plm_resource_db
    ports:
      - "127.0.0.1:5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - innopolois-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: innopolois_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@innopolois.com
      PGADMIN_DEFAULT_PASSWORD: devuser@pass
    ports:
      - "127.0.0.1:5051:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - innopolois-net

  innopolois-plm-server:
    image: midhunx001/innopolois-plm-server:latest
    container_name: innopolois_backend_dev
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "7100:7100"
    networks:
      - innopolois-net
    volumes:
      - ./logs:/app/logs

volumes:
  pgdata:
  pgadmin-data:

networks:
  innopolois-net:
    driver: bridge
